import { wrapper } from '@/app/store'
import ButtonFilter from '@/components/ButtonFilter/ButtonFilter'
import FormTodo from '@/components/FormTodo/FormTodo'
import ListTodo from '@/components/ListTodo/ListTodo'
import SearchTodo from '@/components/SearchTodo/SearchTodo'
import { getListTodo } from '@/features'
import { Container, Space } from '@mantine/core'
import { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container fluid>
        <FormTodo />
        <Space h="lg" />
        <SearchTodo />
        <Space h="lg" />
        <ButtonFilter />
        <Space h="lg" />
        <ListTodo />
      </Container>
    </>
  )
}
Home.getInitialProps = wrapper.getInitialPageProps(({ dispatch }) => async () => {
  await dispatch(getListTodo()).unwrap()
})
export default Home